// <auto-generated />
using System;
using DoctorsClinicApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DoctorsClinicApi.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20210314181746_updateUserRole")]
    partial class updateUserRole
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024");

            modelBuilder.Entity("DoctorsClinicApi.Models.User", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("brithday");

                    b.Property<string>("email");

                    b.Property<string>("gender");

                    b.Property<string>("name");

                    b.Property<byte[]>("passwordHash");

                    b.Property<byte[]>("passwordSalt");

                    b.Property<int>("phone");

                    b.Property<string>("role");

                    b.HasKey("id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("DoctorsClinicApi.Models.Value", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("name");

                    b.HasKey("id");

                    b.ToTable("Values");
                });
#pragma warning restore 612, 618
        }
    }
}
